const BLOG_API = {
  BASE: "http://127.0.0.1:4001/api/v1",
  BASE_AVATAR: "http://127.0.0.1:4001",
  // BASE: "https://pundad.app/api/v1",
  // BASE_AVATAR: "https://pundad.app",

  REGISTER: "/auth/register",
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  REFRESH: "/auth/refresh",
  VERIFY_EMAIL: "/auth/verify-email",
  RESEND_VERIFICATION: "/auth/resend-verification",
  RESETPASSWORD: "/auth/reset-password",
  NEWPASSWORD: "/auth/new-password",
  GCU_DRAFTS: "/posts/drafts",
  USER: "/user",
  USERINPUT: "/user/input",
  POSTS: "/posts",
  COMMENTS: "/comments",
  PUBLISH: "/publish",
  POPULAR: "/popular",
  RANDOM: "/random",
  DAILY: "/daily",
  DAILY_VIEW: "/daily/view",
  BADGE_HISTORY_ME: "/badges/me/history",
  CURRENT_BADGES_ME: "/badges/me/current",
  SEARCH: "/search",
};

export default BLOG_API;